const Dora_Und_Die_Albanische_Staatsgrenze = {
    1: "Das Erste, womit ich bei diesem Projekt angefangen habe.",
    2: "thicc Taubsi",
    3: "._.",
    5: "Das sieht tatsächlich ziemlich cool aus. 🤠",
    8: "Taubsi hat eine Vision.",
    9: "Habe mir für die Inneneinrichtung viel Mühe gegeben. :)",
    10: "Ich wollte Boots erst auf allen Vieren kriechen lassen, aber Gott sei Dank läuft er in der Cartoon-Serie auch Normal. Anthropomorph Boots stets zu Diensten. :D",
    11: "Ich wollte albanische Soldaten an die Grenze stellen und fand unter \"Albaner Skin\" nur Terroristen. Ich hätte das sogar beinahe gelassen, bis Taubsi auf Nachfrage mich korrigiert hat. :)",
    12: "Gottlos.",
    13: "𝘋𝘰𝘳𝘢, 𝘮𝘦𝘪𝘯 𝘚𝘤𝘩𝘢𝘵𝘻. 𝘈𝘭𝘭𝘦𝘴 𝘸𝘪𝘳𝘥 𝘨𝘶𝘵.",
    14: "Verdammte Scheiße.",
    16: "Wollte das eigentlich drin lassen.",
    17: "Boobhunter?",
    18: "😐",
    19: "Dieser Enderman scheint sehr begeistert von Gaskammern zu sein... Warte. Gibt es Gaskammer-Enthusiasmus?",
    20: "Flans Mod...",
    22: "Ah. Endlich.",
    23: "𝘏𝘢𝘭𝘭𝘰",
    26: "Vorsicht, Julius!!!",
    27: "(1) Ich wollte eigentlich einen Abspann machen mit Screenshots, aber besser nicht. Hier zu sehen: Dora/ItsLeMax.",
    28: "(2) Hier noch das Foto von Boots und Julius in \"Normal\".",
    29: "(3) Das Foto von Swiper/Taubsi ist okay, könnte aber besser sein.",
    30: "(4) Diego/leKliiim",
    31: "(5) Kind/Fi05",
    32: "(6) Vater/leBrownie",
    33: "Dora hat gar keine Manieren... Dora The Sexplorer?",
    34: "Attack on Dora",
    35: "Hier noch mal mit 1000-facher Größe.",
    36: "Der finale Film in Premiere. Die Sequenz, wo Taubsi und Ich über mögliche Fortsetzungen geschwärmt haben (der letzte Teil des Kurzfilmes) entstand extern. Die verwendete 40GB AVI wurde gelöscht (siehe rote Farbe)."
};
const Weihnachtsmann_Und_Kokskg = {
    1: "Alles auf Anfang (fast)",
    2: "Hat man leider nicht gesehen. 💔",
    3: "So asozial. Ich liebe es.",
    4: "Das Zimmer ist gut geworden.",
    6: "\"Es kann nicht noch schlimmer werden\"",
    8: "Selbst Trixie hat schon die Schnauze voll.",
    9: "Ich kann nicht mehr.",
    10: "So sahen die Elfen anfangs aus, bis ich später dann doch die Skins überarbeitet habe.",
    13: "So entsteht übrigens South Park",
    14: ":(",
    16: "Jordi ist einfach High.",
    17: "🎵 Ich hab leider nur ein Bein, wollen wir trotzdem Freunde sein? 🎵",
    19: "Ist es ein Vogel! Oder ein Flugzeug! Nein, es ist ein verfickter Nordpol-Mutant.",
    20: "ALIEN!",
    22: "Wollte Jordis Verwandlung animieren, aber...",
    23: "(Verzweifelter Versuch, die Person dick zu machen)",
    24: "WAS IST DAS?",
    26: "Cursed Imagery a la ItsLeMax Maximus",
    27: "Eine schöne Abwechslung vom abgefuckten Alltag.",
    28: "Resource Pack Support für Shader be like",
    30: "So entsteht der manuelle Fokus.",
    31: "Trixie ist ganz schön horny.",
    32: "Der Film in Premiere (Stand: 21.12.2021, nicht final).",
    33: "Ich kann das Video nicht monetarisieren! So ein Scheiß!1! 😡😡😡"
};